version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: user_management_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5433:5432"

  user-management:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user_management_container
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5440
      DATABASE_USER: myuser
      DATABASE_PASSWORD: mypassword
      DATABASE_NAME: user_management_db
    ports:
      - "8080:8080"
    depends_on:
      - postgres